yolo26_detector_node:
  ros__parameters:
    hef_path: "/workspaces/yolo26-hailo/res/models/yolo26n.hef"
    image_topic: "/flir_camera/image_raw"
    bboxdet_topic: "/yolo26/detstream"
    bboxdet_service: "/yolo26/detservice"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.25
    queue_size: 10
