vision/vp_evaluation_node:
  ros__parameters:
    dataset_root: "/workspaces/yolo26-hailo/res/datasets/collection/"
    dataset_name: "coco"
    annotation_file: "instances_val2017.json"

    pub_img_topic: "/vision/detector/fast/img"
    sub_det_topic: "/vision/detector/fast/det"
    stream_rate: 100.0
    buffer_size: 10
